// Copies the canonical GLSL star model (../src/shaders/star.{frag,vert}) into a
// generated TypeScript module so the web renderer uses the exact same source
// as the C CPU evaluator. Runs automatically before `dev`, `build` and `typecheck`.
import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { createHash } from "node:crypto";

const here = dirname(fileURLToPath(import.meta.url));
const shaderDir = resolve(here, "../../src/shaders");
const out = resolve(here, "../lib/shaders/star.generated.ts");

const frag = readFileSync(resolve(shaderDir, "star.frag"), "utf8");
const vert = readFileSync(resolve(shaderDir, "star.vert"), "utf8");
const hash = createHash("sha256").update(frag).digest("hex").slice(0, 16);

mkdirSync(dirname(out), { recursive: true });
writeFileSync(
  out,
  `// GENERATED by scripts/sync_shaders.mjs from src/shaders — do not edit.\n` +
    `export const STAR_FRAG_SHA256 = ${JSON.stringify(hash)};\n` +
    `export const STAR_FRAG = ${JSON.stringify(frag)};\n` +
    `export const STAR_VERT = ${JSON.stringify(vert)};\n`,
);
console.log(`sync_shaders: star.frag (sha256 ${hash}) -> lib/shaders/star.generated.ts`);
